apps/contacts/api/urls.py
from django.urls import path
from .views import ContactList, CommentList

urlpatterns = [
    path('contacts/', ContactList.as_view(), name=ContactList.name),
    path('comments/', CommentList.as_view(), name=CommentList.name),
]

apps/contacts/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = "contacts"

from .views import (
    HomeView, SubjectListView, SubjectCreateView, SubjectUpdateView, SubjectDeleteView,
    ContactListView, ContactCreateView, ContactUpdateView, ContactDeleteView, ContactDetailView,
    CommentCreateView
)

urlpatterns = [
    path('', HomeView.as_view(), name=HomeView.name),

    # Subject
    path('contacts/subjects/', SubjectListView.as_view(), name=SubjectListView.name),
    path('contacts/subjects/create/', SubjectCreateView.as_view(), name=SubjectCreateView.name),
    path('contacts/subjects/update/<int:pk>/', SubjectUpdateView.as_view(), name=SubjectUpdateView.name),
    path('contacts/subjects/delete/<int:pk>/', SubjectDeleteView.as_view(), name=SubjectDeleteView.name),

    # Contact
    path('contacts/contact/', ContactListView.as_view(), name=ContactListView.name),
    path('contacts/contact/create/', ContactCreateView.as_view(), name=ContactCreateView.name),
    path('contacts/contact/update/<int:pk>/', ContactUpdateView.as_view(), name=ContactUpdateView.name),
    path('contacts/contact/delete/<int:pk>/', ContactDeleteView.as_view(), name=ContactDeleteView.name),
    path('contacts/contact/detail/<int:pk>/', ContactDetailView.as_view(), name=ContactDetailView.name),

    # Comment
    path('contacts/contact/detail/<int:pk>/comments/create/', CommentCreateView.as_view(), name=CommentCreateView.name),

]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', include('apps.accounts.urls', namespace='accounts')),
    path('', include('apps.contacts.urls', namespace='contacts')),

    path('accounts/', include('allauth.urls')),

    # Backend API
    path('api/<str:version>/', include('apps.accounts.api.urls')),
    path('api/<str:version>/', include('apps.contacts.api.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.db import models

def create_route_avatar(instance, filename):
    path = 'avatars/{username}/{name}'.format(
        username=instance.username, name=filename
    )
    return path


class PersonAbstract(models.Model):
    """
    Person Abstract model based in profile information
    """

    class GENDER(models.TextChoices):
        NO_SPECIFY = 'no_specify', _('No specify')
        MEN = 'men', _('Men')
        WOMEN = 'women', _('Women')

    class TYPE_DOCUMENT(models.TextChoices):
        NO_SPECIFY = 'no_specify', _('No specify')
        CITIZENDSHIP_CARD = 'citizenship_card', _('Citizenship card')
        IDENTITY_CARD = 'identity_card', _('Identity card')
        FOREIGNER_ID = 'foreigner_id', _('Foreigner ID')
        PASSPORT = 'passport', _('Passport')

    gender = models.CharField(max_length=10, choices=GENDER.choices,
        default=GENDER.NO_SPECIFY, blank=True, null=True, verbose_name=_('gender'))
    address = models.CharField(max_length=30, blank=True, null=True,
        verbose_name=_('address'), help_text=_('residence address.'))
    phone = models.CharField(max_length=30, blank=True, null=True,
        verbose_name=_('Primary phone'), help_text=_('Users phone number.'))
    birth_date = models.DateField(null=True, blank=True, verbose_name=_('birth date'))
    document_number = models.BigIntegerField(null=True, blank=True, unique=True, verbose_name=_('document number'),
        help_text=_('this number is unique and can`t be changed once registered.'))
    type_document = models.CharField(max_length=20, choices=TYPE_DOCUMENT.choices,
        default=TYPE_DOCUMENT.NO_SPECIFY, blank=True, null=True, verbose_name=_('Type document'))
    to_email = models.EmailField(verbose_name=_('to email address'), blank=True, null=True,
        help_text=_('to email address, is the same username'))
    class Meta:
        abstract = True


class User(PersonAbstract, AbstractUser):
    """
    User model based in abstract user for profile information
    """
    avatar = models.ImageField(max_length=255, upload_to=create_route_avatar, blank=True, null=True,
        verbose_name=_('avatar'), help_text=_('profile image of the user'))

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username

    @property
    def get_avatar(self):
        from allauth.account.models import EmailAddress
        user = EmailAddress.objects.filter(email__iexact=self.email).first()
        if user:
            return self.avatar
        elif self.avatar:
            return self.avatar.url
        else:
            return None

apps/contacts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.accounts.models import PersonAbstract, User

class Subject(models.Model):
    """
    Subject model from contacts app`
    """
    name = models.CharField(max_length=60, verbose_name=_('name'),
        help_text=_('descriptive name of subject'))

    class Meta:
        verbose_name = _('Subject')
        verbose_name_plural = _('Subjects')

    def __str__(self):
        return '{}'.format(self.name)


class Contact(PersonAbstract):
    """
    Contact model from contacts app`
    """
    first_name = models.CharField(max_length=30, verbose_name=_('first name'),
        help_text=_('first name'))
    last_name = models.CharField(max_length=150, verbose_name=_('last name'),
        help_text=_('last name'))
    email = models.EmailField(verbose_name=_('email address'),
        help_text=_('email address, is the same username'))
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    message = models.TextField(verbose_name=_('message'), blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True, verbose_name=_('created date'),
        help_text=_('created date'))

    class Meta:
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def get_number_comments(self):
        return self.comment_set.filter(contact_id=self.id).count()


class Comment(models.Model):
    """
    Comment model from contacts app`
    """
    content = models.TextField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True, verbose_name=_('created date'),
        help_text=_('created date'))
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self):
        return '{} comment {}'.format(self.author.username, self.content)

apps/contacts/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.db import transaction
from django.db.models import Q
from django.db import transaction
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import Contact, Subject, Comment
from .forms import ContactForm, SubjectForm, CommentForm
from .tasks import send_contact_mail_registration
from .mixins import ContactMixin


class HomeView(CreateView):
    """
    Register a New contact by form`.
    """
    name = 'home'
    model = Contact
    form_class = ContactForm
    template_name = 'contacts/home.html'
    success_url = reverse_lazy('contacts:home')

    @transaction.atomic
    def form_valid(self, form):
        sid = transaction.savepoint()
        try:
            contact = form.save(commit=False)
            contact.save()
            msg = _('Thank you for entering your personal data..')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            transaction.on_commit(lambda: send_contact_mail_registration.delay(self.request.get_host(), contact.id))
            return super(HomeView, self).form_valid(form)
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super().form_invalid(form)


@method_decorator(login_required, name='dispatch')
class ContactListView(ListView):
    """
    list view for contacts
    """
    name = 'contact_list'
    model = Contact
    paginate_by = 5
    ordering = ["-id"]

    def get_queryset(self):
        """
        Queryset giving only the current contact
        """
        keyword = self.request.GET.get('keyword', None)
        queryset = self.model.objects.all()

        if keyword:
            queryset = self.model.objects.filter(
                Q(first_name__icontains=keyword) |
                Q(last_name__icontains=keyword) |
                Q(gender__icontains=keyword) |
                Q(subject__name__icontains=keyword)
            )
        return queryset


@method_decorator(login_required, name='dispatch')
class ContactCreateView(CreateView):
    """
    create view for contact
    """
    name = 'contact_create'
    form_class = ContactForm
    model = Contact

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and save the users on contacts
        """
        sid = transaction.savepoint()
        try:
            self.object = form.save(commit=False)
            self.object.save()
            form.instance = self.object
            form.save()
            msg = _('Contact has been created successfully.')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            return redirect(reverse_lazy("contacts:contact_list"))
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super(ContactCreateView, self).form_invalid(form)


@method_decorator(login_required, name='dispatch')
class ContactUpdateView(UpdateView):
    """
    update view for contact
    """
    name = 'contact_update'
    form_class = ContactForm
    model = Contact

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and update the contact
        """
        sid = transaction.savepoint()
        try:
            self.object = form.save(commit=False)
            self.object.save()
            form.instance = self.object
            form.save()
            msg = _('User has been updated successfully.')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            return redirect(reverse_lazy("contacts:contact_list"))
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super(ContactUpdateView, self).form_invalid(form)


@method_decorator(login_required, name='dispatch')
class ContactDeleteView(DeleteView):
    """
    delete view for contact
    """
    name = 'contact_delete'
    model = Contact

    def get_success_url(self):
        """
        url to the detail object
        :return: django url
        """
        return reverse_lazy('contacts:contact_list')

@method_decorator(login_required, name='dispatch')
class ContactDetailView(DetailView):
    """
    detail view for contact
    """
    name = 'contact_detail'
    model = Contact
    contact = None

    def dispatch(self, *args, **kwargs):
        self.contact = get_object_or_404(Contact, pk=self.kwargs.get("pk")) if self.kwargs.get("pk", None) else None
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Update the context data with comment form and comment list.
        """
        data = super(ContactDetailView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['comment_form'] = CommentForm(self.request.POST)
        else:
            data['comment_form'] = CommentForm()
        data['comments'] = Comment.objects.filter(contact_id=self.contact.id).order_by('-created_on')
        return data


@method_decorator(login_required, name='dispatch')
class SubjectListView(ListView):
    """
    list view for subject
    """
    name = 'subject_list'
    model = Subject
    paginate_by = 5
    ordering = ["-id"]

    def get_queryset(self):
        """
        Queryset giving only the current subject
        """
        keyword = self.request.GET.get('keyword', None)
        queryset = self.model.objects.all()

        if keyword:
            queryset = self.model.objects.filter(
                Q(name__icontains=keyword)
            )
        return queryset


@method_decorator(login_required, name='dispatch')
class SubjectCreateView(CreateView):
    """
    create view for subject
    """
    name = 'subject_create'
    form_class = SubjectForm
    model = Subject

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and save the users on subjects
        """
        sid = transaction.savepoint()
        try:
            self.object = form.save(commit=False)
            self.object.save()
            form.instance = self.object
            form.save()
            msg = _('Contact has been created successfully.')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            return redirect(reverse_lazy("contacts:subject_list"))
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super(SubjectCreateView, self).form_invalid(form)


@method_decorator(login_required, name='dispatch')
class SubjectUpdateView(UpdateView):
    """
    update view for subject
    """
    name = 'subject_update'
    form_class = SubjectForm
    model = Subject

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and update the subject
        """
        sid = transaction.savepoint()
        try:
            self.object = form.save(commit=False)
            self.object.save()
            form.instance = self.object
            form.save()
            msg = _('User has been updated successfully.')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            return redirect(reverse_lazy("contacts:subject_list"))
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super(SubjectUpdateView, self).form_invalid(form)


@method_decorator(login_required, name='dispatch')
class SubjectDeleteView(DeleteView):
    """
    delete view for subject
    """
    name = 'subject_delete'
    model = Subject

    def get_success_url(self):
        """
        url to the detail object
        :return: django url
        """
        return reverse_lazy('contacts:subject_list')


@method_decorator(login_required, name='dispatch')
class CommentCreateView(ContactMixin, CreateView):
    """
    create view for comment
    """
    name = 'comment_create'
    form_class = CommentForm
    model = Comment

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and save the comments by contact form
        """
        sid = transaction.savepoint()
        try:
            self.object = form.save(commit=False)
            self.object.author_id = self.request.user.id
            self.object.contact_id = self.contact.id
            self.object.save()
            msg = _('Comment has been created successfully.')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            return redirect(reverse_lazy("contacts:contact_detail", kwargs={
                    "pk": self.contact.pk
                }))
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super(CommentCreateView, self).form_invalid(form)

apps/contacts/templates/contacts/contact_confirm_delete.html
{% load i18n %}
<form action="{% url 'contacts:contact_delete' object.id %}" method="post">
    {% csrf_token %}
    <p>{% trans 'Are you sure you want to delete' %} "{{ object }}"?</p>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'close'|title %}</button>
        <button type="submit" class="btn btn-danger" name="{% trans 'delete'|title %}">{% trans 'delete contact'|title %}</button>
    </div>
</form>

apps/contacts/templates/contacts/contact_detail.html
{% extends 'contacts/contacts_base.html' %}
{% load i18n %}
{% block title %}{% trans 'Detail Contact' %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-2">
            {% include 'contacts/utils/_contacts_navbar.html' with active='contact'  %}
        </div>
        <div class="col-10 my-3">

            <div class="card shadow-sm p-2 no-border-radius">
                <div class="card-body">
                    <h5 class="text-center text-blue">{% trans 'Detail Contact' %}</h5>
                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            <h3 class="font-size-30 font-weight-normal text-orange">
                                {{ contact.first_name }} {{ contact.last_name }}
                            </h3>
                            <p><i class="fa fa-envelope mr-2 text-orange"></i> {{ contact.email }}</p>
                        </div>
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            <p><i class="fas fa-venus-mars mr-2 text-orange"></i> {{ contact.get_gender_display }}</p>
                            <p><i class="fas fa-phone mr-2 text-orange"></i> {% if contact.phone %}{{ contact.phone }}{% else %}--{% endif %}</p>
                        </div>
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            <p><i class="far fa-id-card mr-2 mr-2 text-orange"></i> {{ contact.get_type_document_display }}</p>
                            <p><i class="fab fa-creative-commons mr-2 text-orange"></i> {% if contact.document_number %}{{ contact.document_number }}{% else %}--{% endif %}</p>
                        </div>
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            <p><i class="fas fa-birthday-cake mr-2 mr-2 text-orange"></i> {{ contact.birth_date }}</p>
                            <p><i class="far fa-clock mr-2 text-orange"></i> {{ contact.created_on }}</p>
                        </div>
                    </div>
                </div>
            </div>

            {% if messages %}
				{% for message in messages %}
				<div class="text-center alert alert-success" role="alert">
					{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				{% endfor %}
			{% endif %}

            <div class="row">
                <div class="col-5">
                    <form method="post" action="{% url 'contacts:comment_create' contact.pk %}" class="py-2" id="registerform" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <h3 class="text-center mb-0">{% trans "Add Comment" %}</h3>
                        </div>

                        <div class="form-group my-2">
                            <div class="col-12">
                                {{ comment_form.content }}
                                <div class="text-danger">
                                    {{ comment_form.content.errors }}
                                </div>
                            </div>
                        </div>

                        <div class="col-12 my-2 text-left">
                            <a class="btn btn-lg btn-cancel-white text-uppercase mr-2"
                               href="{% url 'contacts:contact_list' %}"
                               name="{% trans 'back'|title %}">{% trans 'back'|title %}
                                <i class="fa fa-chevron-left float-left mr-2 mt-1"></i>
                            </a>
                            <button class="btn btn-save-blue" type="submit">
                                <i class="far fa-comments mr-2"></i> {% trans "submit"|upper %}
                            </button>
                        </div>
                    </form>
                </div>
                <div class="col-7">
                    <div class="form-group">
                        <h3 class="text-center mb-0 py-2">
                            <i class="far fa-comments mr-2"></i>
                            {% trans "Comments" %}
                        </h3>
                    </div>
                    {% if comments %}
                    <h6 class="border-bottom border-gray pb-2 mb-0">Recent updates</h6>
                    {% for obj in comments %}
                    <div class="media text-muted pt-3">
                        <img src="{% if not obj.author.get_avatar %}
                        https://www.library.caltech.edu/sites/default/files/styles/headshot/public/default_images/user.png
                        {% else %}{{ obj.author.get_avatar }}{% endif %}" alt="" width="70" height="70" class="rounded-circle border">
                        <p class="media-body ml-3 pb-3 mb-0 small lh-125 border-bottom border-gray">
                            <strong class="d-block text-gray-dark">@{{ obj.author.username }}</strong>
                            {{ obj.content }}
                            <small class="white-important d-flex full-width flex-row-reverse">
                                {{ obj.created_on }}
                                <i class="fa fa-clock-o mr-2 fa-2x"></i>
                            </small>
                        </p>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/contacts/templates/contacts/contact_list.html
{% extends 'contacts/contacts_base.html' %}
{% load i18n %}
{% block title %}{% trans 'Contact List' %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-2">
            {% include 'contacts/utils/_contacts_navbar.html' with active='contact'  %}
        </div>
        <div class="col-10 my-4">

            <div class="row">
                <div class=" col-12 col-sm-6 col-md-6 col-lg-5 search-bar">
                    <form method="get">
                        <div class="input-group">
                            <input type="text" class="form-control search-round" name="keyword" id="id_keyword" placeholder="{% trans 'search'|title %}" aria-label="{% trans 'search'|title %}" aria-describedby="button-search">
                            <div class="input-group-append">
                                <button class="btn btn-gray-EE" type="submit" id="button-search" data-toggle="tooltip" data-placement="bottom" title="{% trans 'search'|title %}">
                                    <i class="fa fa-search"></i>
                                </button>
                                <a href="{% url 'contacts:contact_list' %}" class="btn btn-gray-EE search-refresh" data-toggle="tooltip" data-placement="bottom" title="{% trans 'clean search'|title %}">
                                    <i class="fas fa-redo-alt"></i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="col-12 col-lg-7 text-right">
                    <a href="{% url 'contacts:contact_create' %}" class="btn btn-blue2 text-uppercase" role="button" aria-pressed="true">
                        {% trans "add contact"|title %}
                        <i class="fa fa-plus float-left mr-2 mt-1"></i>
                    </a>
                </div>
            </div>

            <div class="row bg-white mx-3 mt-5" id="inner_packs" role="tabpanel" aria-labelledby="pills-innerpacks-tab">
                <div class="col-lg-12 px-0">
                    <table class="table table-hover">
                        <thead>
                        <tr class="font-weight-500 table-noborder-l-r text-gray-666">
                            <th scope="col" class="align-middle">{% trans 'id'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'fullname'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'email'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'subject'|title %}</th>
                            <th scope="col" class="align-middle text-center">{% trans 'actions'|title %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for contact in object_list %}
                            {% include 'contacts/utils/_row_contact.html' %}
                        {% empty %}
                            <tr>
                                <td class="text-center" colspan="5">{% trans 'you have no contacts yet' %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'utils/_paginator.html' %}
                    {% include 'accounts/utils/_modal.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
	<script>
		function Delete(url) {
			$('#deleteUser').find('.modal-body').load(url, function () {
				$('#deleteUser').modal({show: true});
			});
		}
	</script>
{% endblock %}

apps/contacts/templates/contacts/contacts_base.html
{% extends 'base.html' %}

apps/contacts/templates/contacts/subject_confirm_delete.html
{% load i18n %}
<form action="{% url 'contacts:subject_delete' object.id %}" method="post">
    {% csrf_token %}
    <p>{% trans 'Are you sure you want to delete' %} "{{ object }}"?</p>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'close'|title %}</button>
        <button type="submit" class="btn btn-danger" name="{% trans 'delete'|title %}">{% trans 'delete subject'|title %}</button>
    </div>
</form>

apps/contacts/templates/contacts/subject_list.html
{% extends 'contacts/contacts_base.html' %}
{% load i18n %}
{% block title %}{% trans 'Subject List' %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-2">
            {% include 'contacts/utils/_contacts_navbar.html' with active='subject'  %}
        </div>
        <div class="col-10 my-4">

            <div class="row">
                <div class=" col-12 col-sm-6 col-md-6 col-lg-5 search-bar">
                    <form method="get">
                        <div class="input-group">
                            <input type="text" class="form-control search-round" name="keyword" id="id_keyword" placeholder="{% trans 'search'|title %}" aria-label="{% trans 'search'|title %}" aria-describedby="button-search">
                            <div class="input-group-append">
                                <button class="btn btn-gray-EE" type="submit" id="button-search" data-toggle="tooltip" data-placement="bottom" title="{% trans 'search'|title %}">
                                    <i class="fa fa-search"></i>
                                </button>
                                <a href="{% url 'contacts:subject_list' %}" class="btn btn-gray-EE search-refresh" data-toggle="tooltip" data-placement="bottom" title="{% trans 'clean search'|title %}">
                                    <i class="fas fa-redo-alt"></i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="col-12 col-lg-7 text-right">
                    <a href="{% url 'contacts:subject_create' %}" class="btn btn-blue2 text-uppercase" role="button" aria-pressed="true">
                        {% trans "add subject"|title %}
                        <i class="fa fa-plus float-left mr-2 mt-1"></i>
                    </a>
                </div>
            </div>

            <div class="row bg-white mx-3 mt-5" id="inner_packs" role="tabpanel" aria-labelledby="pills-innerpacks-tab">
                <div class="col-lg-12 px-0">
                    <table class="table table-hover">
                        <thead>
                        <tr class="font-weight-500 table-noborder-l-r text-gray-666">
                            <th scope="col" class="align-middle">{% trans 'id'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'name'|title %}</th>
                            <th scope="col" class="align-middle text-center">{% trans 'actions'|title %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for subject in object_list %}
                            {% include 'contacts/utils/_row_subject.html' %}
                        {% empty %}
                            <tr>
                                <td class="text-center" colspan="5">{% trans 'you have no subjects yet' %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'utils/_paginator.html' %}
                    {% include 'accounts/utils/_modal.html' %}
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block scripts %}
	<script>
		function Delete(url) {
			$('#deleteUser').find('.modal-body').load(url, function () {
				$('#deleteUser').modal({show: true});
			});
		}
	</script>
{% endblock %}