apps/accounts/api/urls.py
from django.urls import path, include, reverse_lazy

from .views import ApiRoot
from .views import SignupApiView, MyProfileApiView

#app_name = 'api_accounts'

urlpatterns = [
    # Accounts
    path('accounts/my-profile/', MyProfileApiView.as_view(), name='my-profile'),
    path('accounts/signup/', SignupApiView.as_view(), name=SignupApiView.name),

    # Api Root
	path('', ApiRoot.as_view(), name=ApiRoot.name),
]

apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views

from .forms import CustomPasswordResetForm

from .views import (
    LoginView, SignUpView, LogoutView, MyProfile, EditProfileView, PasswordResetConfirmView,
    UserListView, UserCreateView, UserUpdateView, UserDeleteView
)

app_name = "accounts"

urlpatterns = [
    path('accounts/login/', LoginView.as_view(), name=LoginView.name),
    path('accounts/signup/', SignUpView.as_view(), name=SignUpView.name),
    path('accounts/logout/', LogoutView.as_view(), name="logout"),
    path('accounts/password_reset/',
         views.PasswordResetView.as_view(
             template_name='accounts/registration/password_reset_form.html',
             form_class=CustomPasswordResetForm,
             email_template_name='accounts/registration/password_reset_email.html',
             success_url=reverse_lazy('accounts:password_reset_done')
         ), name='password_reset'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView.as_view(
        template_name='accounts/registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', views.PasswordResetCompleteView.as_view(
        template_name = 'accounts/registration/password_reset_complete.html'
    ), name='password_reset_complete'),

    path('accounts/password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Profile
    path('accounts/profile/', MyProfile.as_view(), name=MyProfile.name),
    path('accounts/profile/<int:pk>/', EditProfileView.as_view(), name=EditProfileView.name),

    # User
    path('accounts/users/', UserListView.as_view(), name=UserListView.name),
    path('accounts/users/create/', UserCreateView.as_view(), name=UserCreateView.name),
    path('accounts/users/update/<int:pk>/', UserUpdateView.as_view(), name=UserUpdateView.name),
    path('accounts/users/delete/<int:pk>/', UserDeleteView.as_view(), name=UserDeleteView.name),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', include('apps.accounts.urls', namespace='accounts')),
    path('', include('apps.contacts.urls', namespace='contacts')),

    path('accounts/', include('allauth.urls')),

    # Backend API
    path('api/<str:version>/', include('apps.accounts.api.urls')),
    path('api/<str:version>/', include('apps.contacts.api.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.db import models

def create_route_avatar(instance, filename):
    path = 'avatars/{username}/{name}'.format(
        username=instance.username, name=filename
    )
    return path


class PersonAbstract(models.Model):
    """
    Person Abstract model based in profile information
    """

    class GENDER(models.TextChoices):
        NO_SPECIFY = 'no_specify', _('No specify')
        MEN = 'men', _('Men')
        WOMEN = 'women', _('Women')

    class TYPE_DOCUMENT(models.TextChoices):
        NO_SPECIFY = 'no_specify', _('No specify')
        CITIZENDSHIP_CARD = 'citizenship_card', _('Citizenship card')
        IDENTITY_CARD = 'identity_card', _('Identity card')
        FOREIGNER_ID = 'foreigner_id', _('Foreigner ID')
        PASSPORT = 'passport', _('Passport')

    gender = models.CharField(max_length=10, choices=GENDER.choices,
        default=GENDER.NO_SPECIFY, blank=True, null=True, verbose_name=_('gender'))
    address = models.CharField(max_length=30, blank=True, null=True,
        verbose_name=_('address'), help_text=_('residence address.'))
    phone = models.CharField(max_length=30, blank=True, null=True,
        verbose_name=_('Primary phone'), help_text=_('Users phone number.'))
    birth_date = models.DateField(null=True, blank=True, verbose_name=_('birth date'))
    document_number = models.BigIntegerField(null=True, blank=True, unique=True, verbose_name=_('document number'),
        help_text=_('this number is unique and can`t be changed once registered.'))
    type_document = models.CharField(max_length=20, choices=TYPE_DOCUMENT.choices,
        default=TYPE_DOCUMENT.NO_SPECIFY, blank=True, null=True, verbose_name=_('Type document'))
    to_email = models.EmailField(verbose_name=_('to email address'), blank=True, null=True,
        help_text=_('to email address, is the same username'))
    class Meta:
        abstract = True


class User(PersonAbstract, AbstractUser):
    """
    User model based in abstract user for profile information
    """
    avatar = models.ImageField(max_length=255, upload_to=create_route_avatar, blank=True, null=True,
        verbose_name=_('avatar'), help_text=_('profile image of the user'))

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username

    @property
    def get_avatar(self):
        from allauth.account.models import EmailAddress
        user = EmailAddress.objects.filter(email__iexact=self.email).first()
        if user:
            return self.avatar
        elif self.avatar:
            return self.avatar.url
        else:
            return None

apps/accounts/api/views.py
from django.utils.translation import gettext as _


from rest_framework import status
from rest_framework import permissions
from rest_framework import generics

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.reverse import reverse

from .serializers import UserSerializer

from ..forms import SignUpForm


class SignupApiView(APIView):
    """
    Create a new user and register this account
    """
    name = 'Sign Up'

    def post(self, request, version):
        """
        register a new user
        :param request:
        :param version:
        :return: success or serialized errors
        """
        group = self.request.data.get('group', 'host')
        form = SignUpForm(self.request.POST, self.request.FILES)
        if not form.is_valid():
            errors = dict(form.errors.items())
            return Response([{
                'status': 'error',
                'msg': _('can not create user, data errors'),
                'data': errors
            }],
                status=status.HTTP_400_BAD_REQUEST)
        user_instance = form.save()
        serializer = UserSerializer(user_instance)

        return Response([{
            'status': 'success',
            'msg': _('user {} created successfully.').format(user_instance.get_full_name()),
            'version': version,
            'data': serializer.data
        }],
            status=status.HTTP_200_OK)


class MyProfileApiView(APIView):
    """
    endpoint to retrieve the serializer of the user object
    """
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, version):
        serializer = UserSerializer(self.request.user)
        return Response([{
            'status': 'success',
            'msg': _('profile for user {} retrieved.').format(self.request.user.get_full_name()),
            'version': version,
            'data': serializer.data
        }],
            status=status.HTTP_200_OK)


from apps.contacts.api.views import ContactList, CommentList

class ApiRoot(generics.GenericAPIView):

    name = 'api-root'

    def get(self, request, *args, **kwargs):
        return Response({
            'signup': reverse(SignupApiView.name, request=request, kwargs=kwargs),
            'contacts': reverse(ContactList.name, request=request, kwargs=kwargs),
            'comments': reverse(CommentList.name, request=request, kwargs=kwargs),
        })

apps/accounts/views.py
from django.db.models import Q
from django.db import transaction
from django.urls import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages

from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.utils.translation import get_language, gettext as _
from django.utils.decorators import method_decorator

from django.contrib.auth.decorators import login_required
from django.contrib.auth import views

from .models import User
from .forms import SignUpForm, CustomAuthenticationForm, EditProfileForm, CustomSetPasswordForm, UserDjangoForm
from .tasks import send_mail_registration


class LoginView(views.LoginView):
    name = 'login'
    form_class = CustomAuthenticationForm
    template_name = 'accounts/registration/login.html'

    def get_success_url(self):
        return reverse_lazy('accounts:my_profile')


class LogoutView(views.LogoutView):
    name = 'logout'


class SignUpView(CreateView):
    """
    Register a New user to the app creating a :model:`accounts.User`.
    """
    name = 'signup'
    model = User
    form_class = SignUpForm
    template_name = 'accounts/registration/signup.html'
    success_url = reverse_lazy('accounts:login')

    @transaction.atomic
    def form_valid(self, form):
        """If the form is valid, save the user as inactive and a confirmation email is sent."""
        sid = transaction.savepoint()
        try:
            user = form.save(commit=False)
            user.username = self.request.POST.get('username')
            user.set_password(self.request.POST.get('password'))
            user.save()
            msg = _('Successful registration. Now you can login..')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            transaction.on_commit(lambda: send_mail_registration.delay(self.request.get_host(), user.id))
            return super(SignUpView, self).form_valid(form)
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super().form_invalid(form)


class PasswordResetConfirmView(views.PasswordResetConfirmView):
    form_class = CustomSetPasswordForm
    template_name = 'accounts/registration/password_reset_confirm.html'

    def form_valid(self, form):
        """If the form is valid, save the user as inactive and a confirmation email is sent."""
        form.save()
        msg = _('Your password has been changed successfully!')
        messages.success(self.request, msg)
        return redirect('accounts:login')


@method_decorator(login_required, name='dispatch')
class MyProfile(UpdateView):
    """
    View to see the profile of the user authenticated.
    """
    name = 'my_profile'
    model = User
    form_class = EditProfileForm

    def get_object(self, **kwargs):
        ## this is to get the object without the user id, override the id with the current user
        return get_object_or_404(User, pk=self.request.user.id)

    def get_success_url(self):
        return reverse_lazy('accounts:my_profile')

    @transaction.atomic
    def form_valid(self, form):
        sid = transaction.savepoint()
        try:
            user = form.save(commit=False)
            user.save()
            msg = _('Your profile has been updated successfully.')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            return super(MyProfile, self).form_valid(form)
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super(MyProfile, self).form_invalid(form)


@method_decorator(login_required, name='dispatch')
class EditProfileView(UpdateView):
    """
    View to edit the profile of the user authenticated.
    """
    name = 'edit_profile'
    model = User
    form_class = EditProfileForm
    template_name = 'accounts/user_detail.html'
    success_url = reverse_lazy('accounts:my_profile')

    def form_valid(self, form):
        msg = _('Your profile has been updated successfully.')
        messages.success(self.request, msg)
        return super(EditProfileView, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class UserListView(ListView):
    """
    list view for userss
    """
    name = 'user_list'
    model = User
    paginate_by = 5
    ordering = ["-id"]
    template_name = 'accounts/user_list.html.html'

    def get_queryset(self):
        """
        Queryset giving only the current organization
        """
        keyword = self.request.GET.get('keyword', None)
        queryset = self.model.objects.all()

        if keyword:
            queryset = self.model.objects.filter(
                Q(username__icontains=keyword) |
                Q(email__icontains=keyword) |
                Q(first_name__icontains=keyword) |
                Q(last_name__icontains=keyword)
            )
        return queryset


@method_decorator(login_required, name='dispatch')
class UserCreateView(CreateView):
    """
    create view for user
    """
    name = 'user_create'
    form_class = UserDjangoForm
    model = User
    template_name = 'accounts/user_create.html'

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and save the users on accounts
        """
        sid = transaction.savepoint()
        try:
            self.object = form.save(commit=False)
            self.object.save()
            form.instance = self.object
            form.save()
            msg = _('User has been created successfully.')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            return redirect(reverse_lazy("accounts:user_list"))
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super(UserCreateView, self).form_invalid(form)


@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView):
    """
    update view for user
    """
    name = 'user_update'
    form_class = UserDjangoForm
    model = User
    template_name = 'accounts/user_create.html'

    @transaction.atomic
    def form_valid(self, form, **kwargs):
        """
        Validate and update the user
        """
        sid = transaction.savepoint()
        try:
            self.object = form.save(commit=False)
            self.object.save()
            form.instance = self.object
            form.save()
            msg = _('User has been updated successfully.')
            messages.success(self.request, msg)
            transaction.savepoint_commit(sid)
            return redirect(reverse_lazy("accounts:user_list"))
        except Exception as e:
            messages.error(self.request, e)
            transaction.savepoint_rollback(sid)
        return super(UserUpdateView, self).form_invalid(form)


@method_decorator(login_required, name='dispatch')
class UserDeleteView(DeleteView):
    """
    delete view for user
    """
    name = 'user_delete'
    model = User

    def get_success_url(self):
        """
        url to the detail object
        :return: django url
        """
        return reverse_lazy('accounts:user_list')

apps/accounts/templates/accounts/accounts_base.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'navbar.html' with active='user'  %}
{% endblock %}

apps/accounts/templates/accounts/user_confirm_delete.html
{% load i18n %}
<form action="{% url 'accounts:user_delete' object.id %}" method="post">
    {% csrf_token %}
    <p>{% trans 'Are you sure you want to delete' %} "{{ object }}"?</p>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'close'|title %}</button>
        <button type="submit" class="btn btn-danger" name="{% trans 'delete'|title %}">{% trans 'delete user'|title %}</button>
    </div>
</form>

apps/accounts/templates/accounts/user_create.html
{% extends 'contacts/contacts_base.html' %}
{% load i18n %}
{% block title %}{% trans 'Create User' %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3">
            {% include 'contacts/utils/_contacts_navbar.html' with active='users'  %}
        </div>
        <div class="col-9 my-4">
            <div class="col-12">
                <h5 class="text-center text-gray-666 font-weight-bold font-size-18 text-uppercase mb-4">{% trans 'Create User' %}</h5>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'utils/_form.html' %}
                <div class="row">
				<div class="col-12 my-4 text-right">
                    <a class="btn btn-sm btn-light mr-3" href="{% url 'accounts:user_list' %}" name="{% trans 'cancel'|title %}">{% trans 'cancel'|title %}
                        <i class="fa fa-chevron-left float-left mr-2 mt-1"></i>
                    </a>
                	<button class="btn btn-lg btn-blue2 text-uppercase" type="submit" name="{% if object %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}">
						{% if user %}{% trans 'update'|title %}{% else %}{% trans 'save'|title %}{% endif %}
						<i class="fa fa-save float-left mr-2 mt-1"></i>
					</button>
				</div>
			</div>
            </form>
        </div>
    </div>
{% endblock %}

apps/accounts/templates/accounts/user_form.html
{% extends 'accounts/accounts_base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}
	{% if request.user.id == object.id %}
		{% trans 'My Profile' %} {{ object.get_full_name }}
	{% else %}
		{% trans 'profile of' %} {{ object.get_full_name }}
	{% endif %}
{% endblock %}

{% block styles %}
    {{ form.media.css }}
    {{ form.media.js }}
{% endblock %}

{% block content %}

	<div class="mt-4 px-5">
		{% if messages %}
			{% for message in messages %}
				<div class="text-center alert alert-success" role="alert">
					{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			{% endfor %}
		{% endif %}
	</div>

    <div class=" mb-5">
		<form method="post" enctype="multipart/form-data" class="update-form">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}

			<div class="row mb-5">
				<div class="col-12">
					<div class="card shadow-sm p-5 no-border-radius">
						<div class="card-body">
                            <div class="row">
								<div class="col-12 col-sm-12 col-md-3 col-lg-3">
									<div class="avatar-wrapper my-auto img-avata-bg-big">
										<img class="profile-pic" src="{% if request.user.get_avatar %}
                                        {{ request.user.get_avatar }}{% else %}{% static '/images/user.jpg' %}{% endif %}"/>
										<div class="upload-button">
											<i class="fa fa-arrow-circle-up" aria-hidden="true"></i>
										</div>
										<input class="file-upload" type="file" accept="image/*" name="avatar" id="id_avatar"/>
									</div>
								</div>
								<div class="col-12 col-sm-12 col-md-9 col-lg-9">
									<h3 class="font-size-30 font-weight-normal text-orange">
										{{ form.instance.first_name }} {{ form.instance.last_name }}
									</h3>
                                    <p><i class="fa fa-envelope mr-2 text-orange"></i> {{ form.instance.email }}</p>
                                    <p><i class="fas fa-user mr-2 text-orange"></i> {{ request.user.username }}</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="row equal">
				<div class="col-sm-12 col-md-6 col-lg-6 col-6">
					<div class="card shadow-sm p-5 no-border-radius flex-fill">
						<div class="card-body">
							<div class="row ">

                                <div class="form-group row col-12 mb-4">
                                    <label class="col-sm-4 col-form-label text-gray-666">{{ form.first_name.label }}</label>
                                    <div class="col-sm-8">
                                        {{ form.first_name }}
                                        <div class="text-danger">
                                            {{ form.first_name.errors }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row col-12 mb-4">
                                    <label class="col-sm-4 col-form-label text-gray-666">{{ form.last_name.label }}</label>
                                    <div class="col-sm-8">
                                        {{ form.last_name }}
                                        <div class="text-danger">
                                            {{ form.last_name.errors }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row col-12 mb-4">
                                    <label class="col-sm-4 col-form-label text-gray-666">{{ form.gender.label }}</label>
                                    <div class="col-sm-8">
                                        {{ form.gender }}
                                        <div class="text-danger">
                                            {{ form.gender.errors }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row col-12 mb-4">
                                    <label class="col-sm-4 col-form-label text-gray-666">{{ form.address.label }}</label>
                                    <div class="col-sm-8">
                                        {{ form.address }}
                                        <div class="text-danger">
                                            {{ form.address.errors }}
                                        </div>
                                    </div>
                                </div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-12 col-md-6 col-lg-6 col-6">
					<div class="card shadow-sm p-5 no-border-radius flex-fill">
						<div class="card-body">
							<div class="row">
								<div class="form-group row col-12 mb-4">
                                    <label class="col-sm-4 col-form-label text-gray-666">{{ form.type_document.label }}</label>
                                    <div class="col-sm-8">
                                        {{ form.type_document }}
                                        <div class="text-danger">
                                            {{ form.type_document.errors }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row col-12 mb-4">
                                    <label class="col-sm-4 col-form-label text-gray-666">{{ form.document_number.label }}</label>
                                    <div class="col-sm-8">
                                        {{ form.document_number }}
                                        <div class="text-danger">
                                            {{ form.document_number.errors }}
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group row col-12 mb-4">
                                    <label class="col-sm-4 col-form-label text-gray-666">{{ form.phone.label }}</label>
                                    <div class="col-sm-8">
                                        {{ form.phone }}
                                        <div class="text-danger">
                                            {{ form.phone.errors }}
                                        </div>
                                    </div>
                                </div>

                                {% if request.user.is_superuser %}
                                <div class="form-group row col-12 mb-4">
                                    <label class="col-sm-4 col-form-label text-gray-666">{{ form.to_email.label }}</label>
                                    <div class="col-sm-8">
                                        {{ form.to_email }}
                                        <div class="text-danger">
                                            {{ form.to_email.errors }}
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col text-right">
					<button class="btn btn-save-blue text-uppercase mr-2 mt-2" type="submit">
                    {% trans 'save'|title %}
                    <i class="fa fa-save float-left mr-2 mt-1"></i>
                </button>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

{% block scripts %}
	<script type="text/javascript">
		$(function () {
			var readURL = function (input) {
				if (input.files && input.files[0]) {
					var reader = new FileReader();
					reader.onload = function (e) {
						$('.profile-pic').attr('src', e.target.result);
					};
					reader.readAsDataURL(input.files[0]);
				}
			};

			$(".file-upload").on('change', function () {
				readURL(this);
			});

			$(".upload-button").on('click', function () {
				$(".file-upload").click();
			});
		});
	</script>
{% endblock %}

apps/accounts/templates/accounts/user_list.html
{% extends 'contacts/contacts_base.html' %}
{% load i18n %}
{% block title %}{% trans 'User List' %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-2">
            {% include 'contacts/utils/_contacts_navbar.html' with active='users'  %}
        </div>
        <div class="col-10 my-4">

            <div class="row">
                <div class=" col-12 col-sm-6 col-md-6 col-lg-5 search-bar">
                    <form method="get">
                        <div class="input-group">
                            <input type="text" class="form-control search-round" name="keyword" id="id_keyword" placeholder="{% trans 'search'|title %}" aria-label="{% trans 'search'|title %}" aria-describedby="button-search">
                            <div class="input-group-append">
                                <button class="btn btn-gray-EE" type="submit" id="button-search" data-toggle="tooltip" data-placement="bottom" title="{% trans 'search'|title %}">
                                    <i class="fa fa-search"></i>
                                </button>
                                <a href="{% url 'accounts:user_list' %}" class="btn btn-gray-EE search-refresh" data-toggle="tooltip" data-placement="bottom" title="{% trans 'clean search'|title %}">
                                    <i class="fas fa-redo-alt"></i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="col-12 col-lg-7 text-right">
                    <a href="{% url 'accounts:user_create' %}" class="btn btn-blue2 text-uppercase" role="button" aria-pressed="true">
                        {% trans "add user"|title %}
                        <i class="fa fa-plus float-left mr-2 mt-1"></i>
                    </a>
                </div>
            </div>

            <div class="row bg-white mx-3 mt-5" id="inner_packs" role="tabpanel" aria-labelledby="pills-innerpacks-tab">
                <div class="col-lg-12 px-0">
                    <table class="table table-hover">
                        <thead>
                        <tr class="font-weight-500 table-noborder-l-r text-gray-666">
                            <th scope="col" class="align-middle">{% trans 'id'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'avatar'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'username'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'email'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'fullname'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'gender'|title %}</th>
                            <th scope="col" class="align-middle">{% trans 'phone'|title %}</th>
                            <th scope="col" class="align-middle text-center">{% trans 'actions'|title %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in object_list %}
                            {% include 'accounts/utils/_row_user.html' %}
                        {% empty %}
                            <tr>
                                <td class="" colspan="4">{% trans 'you have no users yet' %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'utils/_paginator.html' %}
                    {% include 'accounts/utils/_modal.html' %}
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block scripts %}
	<script>
		function Delete(url) {
			$('#deleteUser').find('.modal-body').load(url, function () {
				$('#deleteUser').modal({show: true});
			});
		}
	</script>
{% endblock %}